---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-pull-secret
  namespace: mfe-shell
  labels:
    app.kubernetes.io/name: ghcr-pull-secret
    app.kubernetes.io/component: image-pull-credentials
    app.kubernetes.io/part-of: wecoya-platform
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-app-cluster
    kind: ClusterSecretStore
  target:
    name: ghcr-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .token }}","auth":"{{ (printf "%s:%s" .username .token) | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: platform/ghcr/pull-credentials
        property: username
    - secretKey: token
      remoteRef:
        key: platform/ghcr/pull-credentials
        property: token
