apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mfe-shell

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: wecoya-platform
