---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: MFE_NAME-staging-tls
  namespace: MFE_NAME-staging
  labels:
    app.kubernetes.io/name: MFE_NAME-staging-tls
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: wecoya-platform
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  secretName: MFE_NAME-staging-tls
  dnsNames:
    - MFE_NAME-staging.app.wecoya.online
  issuerRef:
    name: letsencrypt-prod-dns01-app
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - digital signature
    - key encipherment
